### PR TITLE
Fixed LICENSE meta name.

### PR DESCRIPTION
**Pull request by manwar**
Hi @srchulo 

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by srchulo** [comment]
Did the license meta name change, or has this always been wrong? I forget what module helper I used for this module, but I believe that was auto-generated. Are you seeing issues with this?

I'm happy to update-- just curious :)

**Comment by manwar** [comment]
> Did the license meta name change, or has this always been wrong? I forget what module helper I used for this module, but I believe that was auto-generated. Are you seeing issues with this?
> 
> I'm happy to update-- just curious :)

For some strange reason, you have to name it differently in each case. In case of dist.ini, you have to write "Artistic_2_0" whereas in Makefile.PL you have to write it as "artistic_2".

**Comment by srchulo** [comment]
Hm. Odd! Thanks for explaining. I can get a new version released on CPAN later tonight.

**Comment by srchulo** [comment]
Sorry for the delay-- release here!

https://metacpan.org/release/SRCHULO/DBIx-Raw-0.17

**Pull request merged**
